site_name: Recherches Embedding
site_url: https://embedding-groupe.github.io/synthese-de-recherche-mkdocs/
nav :
  - Accueil: index.md
  - Contexte et besoins : contexte_besoin.md
  - Recherches génération glossaire: recherches.md
  - Technologie: technologie.md
  - Front-end : front-end.md
  - Parser: parser.md
theme:
  name: material

  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Basculer en mode sombre
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Basculer en mode clair
markdown_extensions:
  - attr_list

extra_css:
  - style/classes.css
  - style/extra.css