site_name: Recherches Embedding
site_url: https://embedding-groupe.github.io/synthese-de-recherche-mkdocs/
nav :
  - Accueil: index.md
  - Contexte et besoins : contexte_besoin.md
  - Recherches génération glossaire: recherches.md
  - Technologie: technologie.md
  - Front-end : front-end.md
  - Parser: parser.md
theme:
  name: material

  palette:
    primary : custom
    accent : custom
markdown_extensions:
  - attr_list

extra_css:
  - style/classes.css
  - style/extra.css