site_name: Recherches Embedding
site_url: https://embedding-groupe.github.io/synthese-de-recherche-mkdocs/
nav :
  - Accueil: index.md
  - Contexte et besoins : contexte_besoin.md
  - Recherches génération glossaire: recherches.md
  - Front-end : front-end.md
theme :
  name: material

  palette:
    - scheme: default
      primary: purple
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Basculer en mode sombre
    - scheme: slate
      primary: purple
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Basculer en mode clair
markdown_extensions:
  - attr_list

extra_css:
  - style/classes.css